### ISSUE TITLE
[Bug]: Issue with minio storage class

### ISSUE THREAD

**Issue by renaudhager** [shopware/helm-charts#26]
### Steps to reproduce

Deploy this helm chart where there is no `standard` storage class and let the default value for storage in minio.

### What should happened?

Kubernetes should creates the PVC

### What actually happened?

PVCs are in a pending state because the `standard` storage does not exist. 
The helm should not have a default value for this, then Kubenetes would use the default storage configured on the cluster.

**Comment by shadracnicholas** [comment]
Resolved with https://github.com/shopware/helm-charts/pull/52
